<?php

namespace Buffalo\Api;

/**
 * Map of generated resource accessors on Client::__call.
 *
 * @internal
 */
final class GeneratedResources
{
    public const MAP = [
        'admin-telegram-bot' => [
            'class' => 'AdminTelegramBotResource',
            'base' => 'admin/telegram-bot',
            'methods' => [
                0 => 'diseaseReportsMap',
            ],
        ],
        'admin-vaccine-consignments' => [
            'class' => 'AdminVaccineConsignmentsResource',
            'base' => 'admin/vaccine-consignments',
            'methods' => [
                0 => 'applyTemplate',
                1 => 'deleteSteps',
                2 => 'deleteUpdates',
                3 => 'destroy',
                4 => 'featured',
                5 => 'getIndex',
                6 => 'index',
                7 => 'publish',
                8 => 'putSteps',
                9 => 'putUpdates',
                10 => 'resyncTemplate',
                11 => 'steps',
                12 => 'stepsComplete',
                13 => 'stepsStart',
                14 => 'stepsUpdates',
                15 => 'store',
                16 => 'templates',
                17 => 'unpublish',
                18 => 'update',
            ],
        ],
        'admin-vaccine-templates' => [
            'class' => 'AdminVaccineTemplatesResource',
            'base' => 'admin/vaccine-templates',
            'methods' => [
                0 => 'active',
                1 => 'destroy',
                2 => 'getIndex',
                3 => 'index',
                4 => 'store',
                5 => 'toggleActive',
                6 => 'update',
            ],
        ],
        'animal-groups' => [
            'class' => 'AnimalGroupsResource',
            'base' => 'animal-groups',
            'methods' => [
                0 => 'createAnimalGroup',
                1 => 'deleteDeleteAnimalGroup',
                2 => 'getBunrAnimalGroups',
                3 => 'mergeAnimalGroups',
                4 => 'patchUpdateAnimalGroup',
                5 => 'searchBunrAnimalGroups',
                6 => 'splitAnimalGroup',
            ],
        ],
        'animal-parent-groups' => [
            'class' => 'AnimalParentGroupsResource',
            'base' => 'animal-parent-groups',
            'methods' => [
                0 => 'addAnimalToFamilyTree',
                1 => 'createParentGroup',
                2 => 'setParents',
            ],
        ],
        'animals' => [
            'class' => 'AnimalsResource',
            'base' => 'animals',
            'methods' => [
                0 => 'animalHasBeenFound',
                1 => 'assignMeasurementToAnimal',
                2 => 'createAnimal',
                3 => 'createAnimalFile',
                4 => 'createAnimalGroup',
                5 => 'createAnimalTag',
                6 => 'createExternalTags',
                7 => 'createMeasurementAttribute',
                8 => 'createMeasurementForAnimal',
                9 => 'createMeasurementType',
                10 => 'deleteAnimal',
                11 => 'deleteAnimalGroup',
                12 => 'deleteAnimalImage',
                13 => 'deleteAnimalTag',
                14 => 'deleteDeleteExternalTag',
                15 => 'editAnimalTag',
                16 => 'editExternalTag',
                17 => 'exportTraceability',
                18 => 'getAllAnimalTags',
                19 => 'getAllAnimals',
                20 => 'getAllMeasurements',
                21 => 'getAnimalByTag',
                22 => 'getAnimalByUuid',
                23 => 'getAnimalFamilyTreeByUuid',
                24 => 'getAnimalHistoryByHistoryId',
                25 => 'getAnimalImages',
                26 => 'getAnimalMeasurementHeadersByUuid',
                27 => 'getAnimalMeasurementValuesByUuid',
                28 => 'getAnimalMeasurementsByUuid',
                29 => 'getAnimalOwnershipHistory',
                30 => 'getAnimalPerformanceData',
                31 => 'getAnimalsByBunrId',
                32 => 'getAnimalsByIsolationId',
                33 => 'getAnimalsByIsolationIdAndBunrUuid',
                34 => 'getAnimalsWithFilters',
                35 => 'getBunrAnimalGroups',
                36 => 'getCreateAnimalTag',
                37 => 'getEditAnimalTag',
                38 => 'getMeasurementAttributes',
                39 => 'getMeasurementByType',
                40 => 'getMeasurementTypes',
                41 => 'getMonthlyBuffaloStats',
                42 => 'getScannedTags',
                43 => 'getSources',
                44 => 'getUpdateAnimalTags',
                45 => 'getUserAnimalTags',
                46 => 'mergeAnimalGroups',
                47 => 'removeAnimalFromFamilyTree',
                48 => 'saveAnimalsFromCsv',
                49 => 'saveAnimalsToWildlifeBlock',
                50 => 'searchAnimalTag',
                51 => 'searchAnimalTagWithGender',
                52 => 'searchAnimals',
                53 => 'searchUserAnimalTag',
                54 => 'splitAnimalGroup',
                55 => 'updateAnimal',
                56 => 'updateAnimalData',
                57 => 'updateAnimalGroup',
                58 => 'updateAnimalMeasurement',
                59 => 'updateAnimalNote',
                60 => 'updateAnimalTags',
                61 => 'updateAttribute',
                62 => 'updateMeasurement',
                63 => 'updateRingNumber',
                64 => 'uploadImages',
            ],
        ],
        'api-roles' => [
            'class' => 'ApiRolesResource',
            'base' => 'api-roles',
            'methods' => [
                0 => 'createRole',
                1 => 'deleteApiRole',
                2 => 'getApiRoles',
                3 => 'getPermissions',
                4 => 'updateRole',
                5 => 'updateUser',
            ],
        ],
        'applications' => [
            'class' => 'ApplicationsResource',
            'base' => 'applications',
            'methods' => [
                0 => 'changeApplicationAuthorizationChain',
                1 => 'createBunrApplication',
                2 => 'deleteBunrApplication',
                3 => 'deleteWarthogPermit',
                4 => 'getAllApplicationHeaders',
                5 => 'getAllApplications',
                6 => 'getAllUserApplications',
                7 => 'getAuthorizationPersons',
                8 => 'getAvailableAuthChainPerson',
                9 => 'getAvailableAuthChainPersons',
                10 => 'getBunrApplicationAuthorizationPersons',
                11 => 'getBunrApplicationByFarmUuid',
                12 => 'getChangeApplicationAuthorizationChain',
                13 => 'getNotifyStateByApplicationUuid',
                14 => 'getWithdrawApplication',
                15 => 'notifyStateByApplicationUuid',
                16 => 'removeBunrApplicationReport',
                17 => 'signBunrApplicationByAuth',
                18 => 'submitBunrApplicationByBuffaloVet',
                19 => 'submitBunrApplicationReport',
                20 => 'submitNewBunrApplicationFiles',
                21 => 'withdrawApplication',
            ],
        ],
        'auth' => [
            'class' => 'AuthResource',
            'base' => 'auth',
            'methods' => [
                0 => 'firebaseOauth',
                1 => 'forgotPassword',
                2 => 'getAuthUser',
                3 => 'login',
                4 => 'reg',
                5 => 'resetPassword',
                6 => 'sendVerificationCode',
                7 => 'sendVerificationEmail',
                8 => 'signOut',
                9 => 'updatePassword',
                10 => 'user',
                11 => 'userWithPermissions',
                12 => 'usersUpdateUserPassword',
                13 => 'verifyCode',
            ],
        ],
        'authorization-chains' => [
            'class' => 'AuthorizationChainsResource',
            'base' => 'authorization-chains',
            'methods' => [
                0 => 'assignPersonWithAuthChainTemplates',
                1 => 'createAuthChain',
                2 => 'createAuthChainMailTemplate',
                3 => 'getAuthChainMailByType',
                4 => 'getAuthorizationChainByContext',
                5 => 'getAuthorizationChainByUuid',
                6 => 'getAuthorizationChains',
                7 => 'getAvailableChainsForPersonLevel',
                8 => 'getExistsAuthPersonChains',
                9 => 'getInfoItemsForMailTemplates',
                10 => 'getParentAuthorizationChains',
                11 => 'getPersonAuthChainTemplates',
                12 => 'notifyVet',
                13 => 'patchEditAuthChainByUuid',
                14 => 'saveAuthorizationChain',
                15 => 'signAuthorizationChainByContext',
            ],
        ],
        'brandmarks' => [
            'class' => 'BrandmarksResource',
            'base' => 'brandmarks',
            'methods' => [
                0 => 'assignBrandmarkToAnimal',
                1 => 'createBrandmark',
                2 => 'deleteBrandmark',
                3 => 'editBrandmark',
                4 => 'getAnimalBrandmark',
                5 => 'getAnimalBrandmarksById',
                6 => 'getAnimalBrandmarksByUuid',
                7 => 'getAvailableBrandmarks',
                8 => 'getPersonBrandmarks',
                9 => 'saveBrandmarkImage',
            ],
        ],
        'bse' => [
            'class' => 'BseResource',
            'base' => 'bse',
            'methods' => [
                0 => 'createBse',
                1 => 'createBseClassMailTemplate',
                2 => 'createBseParameter',
                3 => 'createBseTemplate',
                4 => 'createBseTemplateDisease',
                5 => 'createCertificationType',
                6 => 'deleteBseTemplateClass',
                7 => 'deleteBseTemplateDisease',
                8 => 'deleteCertificationType',
                9 => 'deleteDeleteBseTemplateDisease',
                10 => 'deleteTemplateParameter',
                11 => 'editBseParameter',
                12 => 'editBseTemplate',
                13 => 'editBseTemplateDisease',
                14 => 'editCertificationType',
                15 => 'getAnimalCertificate',
                16 => 'getBseByUuid',
                17 => 'getBseCertificate',
                18 => 'getBseClassMailTemplate',
                19 => 'getBseParameter',
                20 => 'getBseParameters',
                21 => 'getBseParametersForTemplate',
                22 => 'getBseResultNotes',
                23 => 'getBseResults',
                24 => 'getBseTemplateByUuid',
                25 => 'getBseTemplateClasses',
                26 => 'getBses',
                27 => 'getCertificationDiseases',
                28 => 'getCertificationTypeById',
                29 => 'getCertificationTypes',
                30 => 'getCreateBseTemplateDisease',
                31 => 'getCreateCertificationType',
                32 => 'getEditBseTemplateDisease',
                33 => 'getMailTemplateReplacementItems',
                34 => 'getParameterIdentificationMethods',
                35 => 'getParentBseParameters',
                36 => 'getParentCertificationTypes',
                37 => 'getSaveBseResult',
                38 => 'getUserBseTemplates',
                39 => 'getUserBses',
                40 => 'issueBseCertificate',
                41 => 'removeTemplateParameter',
                42 => 'saveBseResult',
                43 => 'saveBseResultNotes',
                44 => 'saveBseTemplateClasses',
                45 => 'saveTemplateParameter',
                46 => 'updateBse',
                47 => 'updateBseClassMailTemplate',
                48 => 'updateBseTemplateClass',
                49 => 'updateTemplateParameter',
                50 => 'updateTemplateParameterOrder',
                51 => 'uploadBseResultPhoto',
                52 => 'uploadBseResultReport',
            ],
        ],
        'commodities' => [
            'class' => 'CommoditiesResource',
            'base' => 'commodities',
            'methods' => [
                0 => 'createCommoditiesMovement',
                1 => 'getSendCommodities',
                2 => 'getSendCommoditiesUuid',
                3 => 'sendCommodities',
                4 => 'sendCommoditiesCheckByCommodityUuid',
            ],
        ],
        'communications' => [
            'class' => 'CommunicationsResource',
            'base' => 'communications',
            'methods' => [
                0 => 'checkForNotification',
                1 => 'createChat',
                2 => 'getTelegramChatMessages',
                3 => 'getTelegramUsers',
                4 => 'getUserChats',
                5 => 'updateChatStatus',
            ],
        ],
        'csv' => [
            'class' => 'CsvResource',
            'base' => 'csv',
            'methods' => [
                0 => 'createNewRowInCsvFile',
                1 => 'parseAnimalsCsvFile',
                2 => 'parseMembersCsvFile',
                3 => 'updateAnimalCsvFile',
            ],
        ],
        'depot-orders' => [
            'class' => 'DepotOrdersResource',
            'base' => 'depot-orders',
            'methods' => [
                0 => 'getAllDepotOrders',
            ],
        ],
        'derivatives' => [
            'class' => 'DerivativesResource',
            'base' => 'derivatives',
            'methods' => [
                0 => 'addDerivativesToGroup',
                1 => 'createAnimalDerivative',
                2 => 'createDerivative',
                3 => 'createDerivativeGroup',
                4 => 'createDerivativeMethod',
                5 => 'deleteDeleteDerivativeFromGroup',
                6 => 'deleteDerivativeFromGroup',
                7 => 'editDerivative',
                8 => 'getAddDerivativesToGroup',
                9 => 'getAllDerivativeMethods',
                10 => 'getAllDerivatives',
                11 => 'getAllDerivativesBySpecies',
                12 => 'getAnimalDerivativeByUuid',
                13 => 'getDerivative',
                14 => 'getDerivativeGroup',
                15 => 'getDerivativeGroups',
                16 => 'getDerivativeMethods',
                17 => 'getFarmAnimalDerivativeByUuid',
                18 => 'getFarmAnimalDerivatives',
                19 => 'saveAnimalDerivativeData',
                20 => 'searchDerivatives',
            ],
        ],
        'devices' => [
            'class' => 'DevicesResource',
            'base' => 'devices',
            'methods' => [
                0 => 'create',
                1 => 'destroy',
                2 => 'devicePersons',
                3 => 'devicesList',
                4 => 'generateGetrequestResponse',
                5 => 'getConfigure',
                6 => 'getDevicePins',
                7 => 'getDevicesConfigure',
                8 => 'getIndex',
                9 => 'linkPerson',
                10 => 'patchSettings',
                11 => 'personDevices',
                12 => 'persons',
                13 => 'pins',
                14 => 'postUpdate',
                15 => 'settings',
                16 => 'settingsCreate',
                17 => 'update',
            ],
        ],
        'disease-risk-models' => [
            'class' => 'DiseaseRiskModelsResource',
            'base' => 'disease-risk-models',
            'methods' => [
                0 => 'getIndex',
                1 => 'getPerformance',
                2 => 'getVersions',
            ],
        ],
        'disease-risk-predictions' => [
            'class' => 'DiseaseRiskPredictionsResource',
            'base' => 'disease-risk-predictions',
            'methods' => [
                0 => 'batch',
                1 => 'dashboard',
                2 => 'getHistory',
                3 => 'highRisk',
                4 => 'modelPerformance',
                5 => 'modelWeights',
                6 => 'statistics',
            ],
        ],
        'diseases' => [
            'class' => 'DiseasesResource',
            'base' => 'diseases',
            'methods' => [
                0 => 'createDisease',
                1 => 'deleteDisease',
                2 => 'getAllDiseases',
                3 => 'getCreateDisease',
                4 => 'getDiseaseByName',
                5 => 'getFmdCountryDaily',
                6 => 'getFmdDailyTrends',
                7 => 'getFmdStats',
                8 => 'getParentDiseases',
                9 => 'searchDisease',
                10 => 'updateDisease',
            ],
        ],
        'farm-disease-risk-timeseries' => [
            'class' => 'FarmDiseaseRiskTimeseriesResource',
            'base' => 'farm-disease-risk-timeseries',
            'methods' => [
                0 => 'farmsCalculate',
                1 => 'getBunrRisks',
                2 => 'getFarmsCompareDiseases',
                3 => 'getFarmsLatest',
                4 => 'getFarmsTimeseries',
                5 => 'getFarmsTrends',
                6 => 'highRisk',
                7 => 'summary',
            ],
        ],
        'farms' => [
            'class' => 'FarmsResource',
            'base' => 'farms',
            'methods' => [
                0 => 'addFileToBunr',
                1 => 'addNatconPermit',
                2 => 'addSpeciesToNatconPermit',
                3 => 'approveNatconPermit',
                4 => 'checkBunr',
                5 => 'checkDefaultFarm',
                6 => 'checkDunevaxFarm',
                7 => 'checkUserFarm',
                8 => 'createNewBunr',
                9 => 'createNewFarm',
                10 => 'createNewFarmApplication',
                11 => 'deleteDeleteBunrCertificate',
                12 => 'deleteDeleteFarmFeatures',
                13 => 'deleteRemoveNatconFile',
                14 => 'findFarmsWithinRadius',
                15 => 'getAdminShapes',
                16 => 'getAllFarms',
                17 => 'getAnimalCampsHistory',
                18 => 'getAnimalCsvFiles',
                19 => 'getAnimalsByCage',
                20 => 'getBunrAuthorizationPersons',
                21 => 'getBunrByUuid',
                22 => 'getBunrFeaturesByBunrUuid',
                23 => 'getBunrNumbers',
                24 => 'getBunrPerson',
                25 => 'getBunrPin',
                26 => 'getFarm',
                27 => 'getFarmAviaries',
                28 => 'getFarmAviaryCages',
                29 => 'getFarmByName',
                30 => 'getFarmByPoint',
                31 => 'getFarmByUuid',
                32 => 'getFarmWildlifeBlocks',
                33 => 'getFarmsByUuid',
                34 => 'getFeatureById',
                35 => 'getFeatureByUuid',
                36 => 'getFmdProtectionZone',
                37 => 'getGenerateBunrFile',
                38 => 'getNatconPermitById',
                39 => 'getNatconPermitLevels',
                40 => 'getNatconPermits',
                41 => 'getNearestFarms',
                42 => 'getPersonBuNrs',
                43 => 'getPersonFarms',
                44 => 'getPortionsByRegionAndTag',
                45 => 'getProvinces',
                46 => 'getProvincesBorder',
                47 => 'getProvincesInfo',
                48 => 'getSpeciesFromNatconPermit',
                49 => 'getStateVetAreaByBunr',
                50 => 'getUserFarms',
                51 => 'getWildlifeBlockAnimals',
                52 => 'importValidatedAnimals',
                53 => 'isItUsersAnimal',
                54 => 'isItUsersFarm',
                55 => 'parseAnimalCsvFile',
                56 => 'patchAddAnimalsToCage',
                57 => 'patchEditBunrData',
                58 => 'patchEditFarmData',
                59 => 'patchSaveFarmFeatures',
                60 => 'patchSavePersonBunrs',
                61 => 'patchSetDefaultFarm',
                62 => 'patchSetDunevaxFarm',
                63 => 'patchSetNatconServiceProvider',
                64 => 'patchUpdateFarmBorders',
                65 => 'patchUpdateFeatureById',
                66 => 'rejectNatconPermit',
                67 => 'saveAnimalCsvFile',
                68 => 'saveAviaryCage',
                69 => 'saveAviaryCageSeries',
                70 => 'searchBunrFeature',
                71 => 'searchFarmByBunr',
                72 => 'searchFeaturesByFeatureName',
                73 => 'searchNatconPermits',
                74 => 'searchUserFarms',
                75 => 'updateNatconPermitInfo',
                76 => 'updateNatconPermitSpecies',
                77 => 'uploadNatconFile',
            ],
        ],
        'features' => [
            'class' => 'FeaturesResource',
            'base' => 'features',
            'methods' => [
                0 => 'getAnimalCampsHistory',
                1 => 'getBunrFeatures',
                2 => 'getFeatureByUuid',
                3 => 'getWildlifeBlockAnimals',
                4 => 'searchBunrFeatures',
                5 => 'searchFeaturesByFeatureName',
            ],
        ],
        'feedlot' => [
            'class' => 'FeedlotResource',
            'base' => 'feedlot',
            'methods' => [
                0 => 'intake',
                1 => 'releaseRfid',
            ],
        ],
        'files' => [
            'class' => 'FilesResource',
            'base' => 'files',
            'methods' => [
                0 => 'deleteFile',
                1 => 'deleteFileFromRound',
                2 => 'deletePersonFile',
                3 => 'downloadFile',
                4 => 'getAllFileTypes',
                5 => 'getAllFiles',
                6 => 'getCsvParserTypes',
                7 => 'getDownloadFile',
                8 => 'getFileByName',
                9 => 'getFilePath',
                10 => 'getFileTypes',
                11 => 'getFilesByFileType',
                12 => 'getLabPdfFileFileTypes',
                13 => 'getLabPdfFileTypes',
                14 => 'getLabPdfKeys',
                15 => 'getPersonFiles',
                16 => 'getSaveFile',
                17 => 'saveFile',
                18 => 'savePersonFile',
                19 => 'searchFile',
                20 => 'searchPersonFile',
                21 => 'storeFile',
                22 => 'storeFiles',
                23 => 'updateTemporaryTypes',
            ],
        ],
        'google2fa' => [
            'class' => 'Google2faResource',
            'base' => 'google2fa',
            'methods' => [
                0 => 'debug',
                1 => 'get',
                2 => 'recover',
                3 => 'recoverCode',
                4 => 'verifCode',
                5 => 'verify',
            ],
        ],
        'hunts' => [
            'class' => 'HuntsResource',
            'base' => 'hunts',
            'methods' => [
                0 => 'addHuntToHuntingPeriod',
                1 => 'addHuntingPeriod',
                2 => 'getAllOutfitterHuntingPeriods',
                3 => 'getHuntByHunter',
                4 => 'getHuntingPeriodsByOutfitter',
                5 => 'getPartsOfTrophy',
                6 => 'getPartsOfTrophyByHunt',
            ],
        ],
        'icc-device' => [
            'class' => 'IccDeviceResource',
            'base' => 'icc-device',
            'methods' => [
                0 => 'all',
                1 => 'destroy',
                2 => 'getIndex',
                3 => 'update',
            ],
        ],
        'integrations' => [
            'class' => 'IntegrationsResource',
            'base' => 'integrations',
            'methods' => [
                0 => 'aimsAuth',
                1 => 'myhuntAuth',
                2 => 'sosAuth',
            ],
        ],
        'isolations' => [
            'class' => 'IsolationsResource',
            'base' => 'isolations',
            'methods' => [
                0 => 'addNewAnimalsInRound',
                1 => 'addNewRound',
                2 => 'animalIsolationStats',
                3 => 'closeIsolation',
                4 => 'createInstituteRef',
                5 => 'createIsolation',
                6 => 'createIsolationRound',
                7 => 'createLabRef',
                8 => 'deleteAnimalsFromRound',
                9 => 'deleteDeleteTestFromRound',
                10 => 'deleteIsolation',
                11 => 'editIsolationTestResult',
                12 => 'export',
                13 => 'getAllIsolations',
                14 => 'getAllRoundDetails',
                15 => 'getAuctionReport',
                16 => 'getAvailableIsolationsForUser',
                17 => 'getAvailableProtocolTests',
                18 => 'getCittResults',
                19 => 'getCittTester',
                20 => 'getCreateIsolation',
                21 => 'getExtraTestDates',
                22 => 'getIsolationAnimalsByBunr',
                23 => 'getIsolationAnimalsByBunrAndSpecies',
                24 => 'getIsolationAnimalsByIsolationId',
                25 => 'getIsolationByBunr',
                26 => 'getIsolationByBunrUuid',
                27 => 'getIsolationById',
                28 => 'getIsolationRoundByIsolationId',
                29 => 'getIsolationStatistics',
                30 => 'getIsolationsForSpecificPersons',
                31 => 'getLabTestResultsHeaders',
                32 => 'getLabTestResultsItems',
                33 => 'getLabUserIsolation',
                34 => 'getPurposeOfTestingAndSpecimens',
                35 => 'getRoundAnimals',
                36 => 'getRoundFiles',
                37 => 'getRoundRefs',
                38 => 'getTbReport',
                39 => 'getTbReports',
                40 => 'getUpdateIsolation',
                41 => 'getUserSpecificRound',
                42 => 'lockIsolation',
                43 => 'monthlyIsolationMetrics',
                44 => 'newCumulativeIsolations',
                45 => 'postSearchIsolation',
                46 => 'postSearchMyIsolation',
                47 => 'removeFromIsolation',
                48 => 'saveAnimalTestResultsFile',
                49 => 'saveAnimalTestResultsFileForSpecificResult',
                50 => 'saveLabToIsolationRoundTest',
                51 => 'saveParentTestResultFile',
                52 => 'saveProtocolToIsolationRound',
                53 => 'saveRoundTestResult',
                54 => 'saveSampleRef',
                55 => 'saveSpecimens',
                56 => 'saveTbResults',
                57 => 'saveTestResultsFile',
                58 => 'saveTestResultsFileForSpecificResult',
                59 => 'saveToIsolation',
                60 => 'searchAvailableIsolationsForUser',
                61 => 'searchIsolation',
                62 => 'searchMyIsolation',
                63 => 'setExtraTestDate',
                64 => 'setNegativeResult',
                65 => 'setPurposeOfTesting',
                66 => 'signCittResults',
                67 => 'unlockIsolation',
                68 => 'updateAnimalOrder',
                69 => 'updateCittExtraData',
                70 => 'updateExtraTestDates',
                71 => 'updateIsolation',
                72 => 'updateOwnerRef',
                73 => 'updateRoundRefs',
            ],
        ],
        'kmz' => [
            'class' => 'KmzResource',
            'base' => 'kmz',
            'methods' => [
                0 => 'createKmzFile',
                1 => 'createPolygonFromKmz',
                2 => 'getKmzZones',
            ],
        ],
        'kmz-files' => [
            'class' => 'KmzFilesResource',
            'base' => 'kmz-files',
            'methods' => [
                0 => 'create',
                1 => 'createPolygon',
                2 => 'zones',
            ],
        ],
        'lab-pdf-files' => [
            'class' => 'LabPdfFilesResource',
            'base' => 'lab-pdf-files',
            'methods' => [
                0 => 'generateMovementFile',
                1 => 'generateResultsFile',
            ],
        ],
        'labs' => [
            'class' => 'LabsResource',
            'base' => 'labs',
            'methods' => [
                0 => 'getAvailableLabByTestName',
                1 => 'getAvailableLabMethodsByAnimalTag',
                2 => 'getAvailableLabsByTestName',
                3 => 'getLabProperties',
                4 => 'storeLabProperties',
            ],
        ],
        'mails' => [
            'class' => 'MailsResource',
            'base' => 'mails',
            'methods' => [
                0 => 'emailAccessLog',
                1 => 'getBunrApplicationMailFilters',
                2 => 'getBunrApplicationMails',
                3 => 'getBunrApplicationMailsByFilters',
                4 => 'getMailFilters',
                5 => 'getMailsByFilters',
                6 => 'getMovementMailFilters',
                7 => 'getMovementMails',
                8 => 'getMovementMailsByFilters',
                9 => 'mailAccess',
                10 => 'searchBunrApplicationMails',
                11 => 'searchMailAccess',
                12 => 'searchMovementMails',
            ],
        ],
        'map-risks' => [
            'class' => 'MapRisksResource',
            'base' => 'map-risks',
            'methods' => [
                0 => 'getRiskZonesExportKml',
                1 => 'getRiskZonesExportKmz',
                2 => 'outbreakData',
                3 => 'riskZones',
                4 => 'weatherData',
            ],
        ],
        'mapbox' => [
            'class' => 'MapboxResource',
            'base' => 'mapbox',
            'methods' => [
                0 => 'directions',
            ],
        ],
        'marketplace' => [
            'class' => 'MarketplaceResource',
            'base' => 'marketplace',
            'methods' => [
                0 => 'cart',
                1 => 'cartItems',
                2 => 'catalog',
                3 => 'checkout',
                4 => 'deleteCartItems',
                5 => 'fulfillmentsDispatch',
                6 => 'fulfillmentsPack',
                7 => 'fulfillmentsPick',
                8 => 'getCatalog',
                9 => 'getListings',
                10 => 'getOrders',
                11 => 'getOrdersPayments',
                12 => 'getPrescriptions',
                13 => 'getPrescriptionsPdf',
                14 => 'getPrescriptionsVerify',
                15 => 'getShipments',
                16 => 'getSubOrders',
                17 => 'getSuppliers',
                18 => 'getSuppliersIntegrations',
                19 => 'getSuppliersLedger',
                20 => 'listings',
                21 => 'listingsBarcodes',
                22 => 'listingsPrices',
                23 => 'listingsStock',
                24 => 'orders',
                25 => 'ordersCancel',
                26 => 'ordersPermits',
                27 => 'paymentsInitiate',
                28 => 'paymentsPayfastCancel',
                29 => 'paymentsPayfastIpn',
                30 => 'paymentsPayfastSuccess',
                31 => 'paymentsStripeWebhook',
                32 => 'postListings',
                33 => 'postPrescriptions',
                34 => 'postRegulatoryRules',
                35 => 'postSuppliers',
                36 => 'postTradeRestrictions',
                37 => 'postWarehouses',
                38 => 'prescriptions',
                39 => 'prescriptionsAttach',
                40 => 'prescriptionsAuthPreference',
                41 => 'prescriptionsReject',
                42 => 'prescriptionsSign',
                43 => 'prescriptionsWhatsappOtp',
                44 => 'putCartItems',
                45 => 'putListings',
                46 => 'putPrescriptionsAuthPreference',
                47 => 'putRegulatoryRules',
                48 => 'putSuppliers',
                49 => 'putTradeRestrictions',
                50 => 'putWarehouses',
                51 => 'regulatoryRules',
                52 => 'subOrdersCancel',
                53 => 'subOrdersConfirmDelivery',
                54 => 'subOrdersFulfillment',
                55 => 'subOrdersInvoice',
                56 => 'subOrdersRevertDelivery',
                57 => 'subOrdersShipments',
                58 => 'supplierSubOrdersAccept',
                59 => 'supplierSubOrdersShip',
                60 => 'supplierWebhook',
                61 => 'suppliers',
                62 => 'suppliersIntegrations',
                63 => 'suppliersMy',
                64 => 'suppliersPayouts',
                65 => 'suppliersUsers',
                66 => 'trackingWebhook',
                67 => 'tradeRestrictions',
                68 => 'vcprCheck',
                69 => 'vetPrescriptions',
                70 => 'warehouses',
            ],
        ],
        'medicine' => [
            'class' => 'MedicineResource',
            'base' => 'medicine',
            'methods' => [
                0 => 'animalTreatments',
                1 => 'assignMedicineToAnimals',
                2 => 'create',
                3 => 'createMedicine',
                4 => 'createMedicineBatch',
                5 => 'createMedicineType',
                6 => 'deleteDelete',
                7 => 'deleteDeleteMedicineType',
                8 => 'deleteMedicine',
                9 => 'deleteMedicineBatch',
                10 => 'deleteMedicineType',
                11 => 'getManufacturers',
                12 => 'getMedicine',
                13 => 'getMedicineBatch',
                14 => 'getMedicineBatchForCitt',
                15 => 'getMedicineBatchInfoList',
                16 => 'getMedicineBatches',
                17 => 'getMedicineForCitt',
                18 => 'getMedicineInfo',
                19 => 'getMedicineInfoList',
                20 => 'getMedicineType',
                21 => 'getMedicineTypesList',
                22 => 'getMedicinesFromBatch',
                23 => 'getMedicinesList',
                24 => 'getVaccineTypesWithMedicines',
                25 => 'patchUpdate',
                26 => 'patchUpdateMedicineType',
                27 => 'search',
                28 => 'searchBatchByType',
                29 => 'searchMedicine',
                30 => 'searchMedicineBatch',
                31 => 'searchMedicineType',
                32 => 'setMedicineBatchForCitt',
                33 => 'setMedicineForCitt',
                34 => 'updateMedicine',
                35 => 'updateMedicineBatch',
                36 => 'updateMedicineType',
            ],
        ],
        'medicine-batches' => [
            'class' => 'MedicineBatchesResource',
            'base' => 'medicine-batches',
            'methods' => [
                0 => 'create',
                1 => 'deleteDelete',
                2 => 'getManufacturers',
                3 => 'getMedicineBatch',
                4 => 'getMedicineBatchForCitt',
                5 => 'getMedicineBatchInfo',
                6 => 'getMedicineBatchInfoList',
                7 => 'getMedicineBatches',
                8 => 'patchUpdate',
                9 => 'search',
                10 => 'searchByType',
                11 => 'setMedicineBatchForCitt',
            ],
        ],
        'medicine-packages' => [
            'class' => 'MedicinePackagesResource',
            'base' => 'medicine-packages',
            'methods' => [
                0 => 'askForPermission',
                1 => 'assignBoxToDepo',
                2 => 'assignUserToScanHistory',
                3 => 'availableUuids',
                4 => 'bulkCreateBox',
                5 => 'createGovOrder',
                6 => 'destroy',
                7 => 'getArchive',
                8 => 'getGetPackageParent',
                9 => 'getGovOrder',
                10 => 'getIndex',
                11 => 'getUuid',
                12 => 'packBottles',
                13 => 'packagesStatuses',
                14 => 'repackBottle',
                15 => 'scanQrCode',
                16 => 'scanQrCodeHistory',
                17 => 'sealPackage',
                18 => 'update',
                19 => 'updateGovOrder',
                20 => 'uploadTemperatureFile',
            ],
        ],
        'misc' => [
            'class' => 'MiscResource',
            'base' => '',
            'methods' => [
                0 => 'agroEcologicalZones',
                1 => 'assignMovementAuthorizationLevels',
                2 => 'assignZones',
                3 => 'checkBUNr',
                4 => 'countries',
                5 => 'createMovementAuthLevel',
                6 => 'deleteMovementAuthLevel',
                7 => 'deleteVaccineSubscriptions',
                8 => 'devices',
                9 => 'diseaseOutbreaks',
                10 => 'diseaseRiskModels',
                11 => 'firebaseOauth',
                12 => 'forgotPassword',
                13 => 'getBunrCountry',
                14 => 'getCsvParserTypes',
                15 => 'getMovementAuthorizationLevel',
                16 => 'getMovementAuthorizations',
                17 => 'getPersonsByFarms',
                18 => 'getPersonsZones',
                19 => 'getRequestedCalls',
                20 => 'getStateVets',
                21 => 'getUserWithLevel',
                22 => 'getVacancyApplications',
                23 => 'getZonesForPerson',
                24 => 'getZonesTypes',
                25 => 'google2fa',
                26 => 'iccDevice',
                27 => 'jobApplications',
                28 => 'medicinePackages',
                29 => 'monthlystatereport',
                30 => 'movementAuthorizationLevels',
                31 => 'movementAuthorizationZones',
                32 => 'outbreaks',
                33 => 'ping',
                34 => 'postDevices',
                35 => 'postIccDevice',
                36 => 'postMedicinePackages',
                37 => 'postVaccineRequests',
                38 => 'postVaccineSubscriptions',
                39 => 'products',
                40 => 'provinces',
                41 => 'removePersonZones',
                42 => 'resetPassword',
                43 => 'scannerDevices',
                44 => 'searchCountries',
                45 => 'sendIsolationEmails',
                46 => 'sendUsMessage',
                47 => 'shapesAbattoirsZones',
                48 => 'shapesAdminsZones',
                49 => 'shapesFmdZones',
                50 => 'signMovementAuthorization',
                51 => 'testScanner',
                52 => 'updatePersonsChain',
                53 => 'updateRequestedCallStatus',
                54 => 'updateSignature',
                55 => 'updateUserLevel',
                56 => 'userMovementAuthorizationZones',
                57 => 'users',
                58 => 'vacancyApplications',
                59 => 'vaccineRequests',
                60 => 'vaccineSubscriptions',
                61 => 'vaccineTracking',
                62 => 'vetContact',
            ],
        ],
        'movement-authorization' => [
            'class' => 'MovementAuthorizationResource',
            'base' => 'movement-authorization',
            'methods' => [
                0 => 'assignLevelsAndZones',
                1 => 'createLevel',
                2 => 'deleteDeleteLevel',
                3 => 'getLevel',
                4 => 'getLevels',
                5 => 'getPersonsZones',
                6 => 'getUserWithLevel',
                7 => 'getUserZones',
                8 => 'getZones',
                9 => 'getZonesForPerson',
                10 => 'getZonesTypes',
                11 => 'patchUpdateUserLevel',
            ],
        ],
        'movements' => [
            'class' => 'MovementsResource',
            'base' => 'movements',
            'methods' => [
                0 => 'addVehicle',
                1 => 'approveMovement',
                2 => 'createMovement',
                3 => 'declineMovement',
                4 => 'getAllMovements',
                5 => 'getAnimalMovements',
                6 => 'getApplicationCumulativeStats',
                7 => 'getApplicationStats',
                8 => 'getMovementAuthorizations',
                9 => 'getMovementByRef',
                10 => 'getMovementStatuses',
                11 => 'getRemoveMovementFile',
                12 => 'getSaveAdditionalInfo',
                13 => 'getStateVets',
                14 => 'getUpdateMovementStatus',
                15 => 'getUserMovements',
                16 => 'notifySendersState',
                17 => 'postSearchMovement',
                18 => 'postSearchMyMovement',
                19 => 'removeMovementFile',
                20 => 'removeVehicle',
                21 => 'saveAdditionalInfo',
                22 => 'saveMovementAuthFile',
                23 => 'saveMovementGates',
                24 => 'saveRedcrossPermitsFile',
                25 => 'saveTimeData',
                26 => 'searchMovement',
                27 => 'searchMyMovement',
                28 => 'sendRecommendationToMoveFile',
                29 => 'showRecommendationToMove',
                30 => 'signMovementAuthorization',
                31 => 'updateMovementStatus',
                32 => 'updatePersonsChain',
                33 => 'uploadMovementRecFile',
                34 => 'verifiedMovementRecFile',
                35 => 'verifyMovementAuthFile',
            ],
        ],
        'mysql-commands' => [
            'class' => 'MysqlCommandsResource',
            'base' => 'mysql-commands',
            'methods' => [
                0 => 'getAllCommands',
                1 => 'getCommandData',
            ],
        ],
        'natcon-permits' => [
            'class' => 'NatconPermitsResource',
            'base' => 'natcon-permits',
            'methods' => [
                0 => 'approve',
                1 => 'get',
                2 => 'getLevels',
                3 => 'patchUpdateInfo',
                4 => 'patchUpdateSpecies',
                5 => 'reject',
            ],
        ],
        'orders' => [
            'class' => 'OrdersResource',
            'base' => 'orders',
            'methods' => [
                0 => 'get',
                1 => 'getAll',
                2 => 'getAllOrders',
                3 => 'getOrder',
            ],
        ],
        'outbreaks' => [
            'class' => 'OutbreaksResource',
            'base' => 'outbreaks',
            'methods' => [
                0 => 'diseases',
                1 => 'events',
                2 => 'getIndex',
                3 => 'list',
                4 => 'nearby',
                5 => 'statistics',
                6 => 'timeline',
            ],
        ],
        'payments' => [
            'class' => 'PaymentsResource',
            'base' => 'payments',
            'methods' => [
                0 => 'cancel',
                1 => 'cancelSubscription',
                2 => 'ipn',
                3 => 'payCart',
                4 => 'payOnce',
                5 => 'subscribe',
                6 => 'subscribeByMembers',
                7 => 'success',
            ],
        ],
        'permissions' => [
            'class' => 'PermissionsResource',
            'base' => 'permissions',
            'methods' => [
                0 => 'checkUserRolePermission',
                1 => 'createRoleWithPermissions',
                2 => 'deleteDeleteRole',
                3 => 'editRole',
                4 => 'getAllPermissionForPersons',
                5 => 'getAllPermissions',
                6 => 'getAllPermissionsNames',
                7 => 'getPersonPermissions',
                8 => 'getRoleById',
                9 => 'getRoleByName',
                10 => 'getRoles',
                11 => 'hasUserAccessToCreateBseTemplate',
                12 => 'savePersonPermissions',
            ],
        ],
        'person-brandmarks' => [
            'class' => 'PersonBrandmarksResource',
            'base' => 'person-brandmarks',
            'methods' => [
                0 => 'assignToAnimal',
                1 => 'create',
                2 => 'deleteDelete',
                3 => 'getAnimalBrandmark',
                4 => 'getAnimalBrandmarksById',
                5 => 'getAnimalBrandmarksByUuid',
                6 => 'getAvailable',
                7 => 'getPersonBrandmarks',
                8 => 'patchEdit',
            ],
        ],
        'person-documents' => [
            'class' => 'PersonDocumentsResource',
            'base' => 'person-documents',
            'methods' => [
                0 => 'approve',
                1 => 'deleteRemove',
                2 => 'getDocument',
                3 => 'getDocumentTypes',
                4 => 'getDocuments',
                5 => 'getDocumentsForValidation',
                6 => 'getHuntingLicenseTypes',
                7 => 'reject',
                8 => 'upload',
            ],
        ],
        'person-mail-templates' => [
            'class' => 'PersonMailTemplatesResource',
            'base' => 'person-mail-templates',
            'methods' => [
                0 => 'create',
                1 => 'createMailTemplate',
                2 => 'get',
                3 => 'getEnumValues',
                4 => 'getMailTemplate',
                5 => 'getMailTemplateReplacementItems',
                6 => 'getMailTemplatesEnum',
                7 => 'getReplacementItems',
                8 => 'patchUpdate',
                9 => 'updateMailTemplate',
            ],
        ],
        'person-members' => [
            'class' => 'PersonMembersResource',
            'base' => 'person-members',
            'methods' => [
                0 => 'addMembers',
                1 => 'addMembersByCsvFile',
                2 => 'addWithCsv',
                3 => 'deleteDelete',
                4 => 'deleteDeleteMemberFromPerson',
                5 => 'getAll',
                6 => 'getAllPersonMembers',
                7 => 'parseCsv',
                8 => 'save',
                9 => 'savePersonMember',
            ],
        ],
        'person-roles' => [
            'class' => 'PersonRolesResource',
            'base' => 'person-roles',
            'methods' => [
                0 => 'createPersonUserRole',
                1 => 'deleteDeletePersonUserRole',
                2 => 'editUsersPersonRole',
                3 => 'getLabUserPermissions',
                4 => 'getPersonUserRoles',
                5 => 'setPersonUserRoleForUser',
                6 => 'updatePersonUserRole',
            ],
        ],
        'person-telegram-bots' => [
            'class' => 'PersonTelegramBotsResource',
            'base' => 'person-telegram-bots',
            'methods' => [
                0 => 'addCommands',
                1 => 'addCommandsToBot',
                2 => 'create',
                3 => 'createTelegramBot',
                4 => 'deleteDeleteUser',
                5 => 'deleteUserFromBot',
                6 => 'getBotCommandsList',
                7 => 'getBotUsers',
                8 => 'getCommandsList',
                9 => 'getPersonTelegramQr',
                10 => 'getQr',
                11 => 'getUsers',
                12 => 'webhook',
            ],
        ],
        'person-user-roles' => [
            'class' => 'PersonUserRolesResource',
            'base' => 'person-user-roles',
            'methods' => [
                0 => 'createPersonUserRole',
                1 => 'deletePersonUserRole',
                2 => 'getLabUserPermissions',
                3 => 'getPersonUserRoles',
                4 => 'setPersonUserRoleForUser',
                5 => 'updatePersonUserRole',
            ],
        ],
        'persons' => [
            'class' => 'PersonsResource',
            'base' => 'persons',
            'methods' => [
                0 => 'addPassportInfo',
                1 => 'addUsersToPerson',
                2 => 'allowAppForPermit',
                3 => 'apiUsersList',
                4 => 'approvePersonDocument',
                5 => 'byCoords',
                6 => 'checkPerson',
                7 => 'checkPersonIdentifier',
                8 => 'checkPersonRef',
                9 => 'checkWarthogPermitSigned',
                10 => 'companiesAndNaturalPersons',
                11 => 'countries',
                12 => 'createPerson',
                13 => 'createVehicle',
                14 => 'decodeBarcode',
                15 => 'deleteDeleteDriver',
                16 => 'deleteDeleteUsersFromPerson',
                17 => 'deleteDeleteVehicle',
                18 => 'deletePerson',
                19 => 'denyAppForPermit',
                20 => 'generateUserAgreement',
                21 => 'getAllBuwrCertificateRequests',
                22 => 'getAllIssuedPermitsByAuthCode',
                23 => 'getAllLabs',
                24 => 'getAllNaturalPersons',
                25 => 'getApiUsers',
                26 => 'getApplicationsForPermits',
                27 => 'getAuthChainPersonsByLevels',
                28 => 'getAuthChainPersonsByTemplateId',
                29 => 'getAvailableMemberUserPersons',
                30 => 'getCertificateEmails',
                31 => 'getCheckPersonIdentifier',
                32 => 'getCheckPersonRef',
                33 => 'getCittTesterPersons',
                34 => 'getClients',
                35 => 'getCreateVehicle',
                36 => 'getDepoOrders',
                37 => 'getDocumentById',
                38 => 'getDocumentsForValidation',
                39 => 'getDriver',
                40 => 'getGeneratePersonFile',
                41 => 'getHuntingLicenseTypes',
                42 => 'getInviteMessageForMessengers',
                43 => 'getIssuerPersons',
                44 => 'getLabMethods',
                45 => 'getMonthlyPersonStats',
                46 => 'getNaturalPersons',
                47 => 'getNaturalPersonsList',
                48 => 'getOutfitters',
                49 => 'getPerson',
                50 => 'getPersonAgreement',
                51 => 'getPersonByPersonEmail',
                52 => 'getPersonByUserUd',
                53 => 'getPersonByUuid',
                54 => 'getPersonDocumentTypes',
                55 => 'getPersonDocuments',
                56 => 'getPersonEntityTypes',
                57 => 'getPersonFilesByBunr',
                58 => 'getPersonIdentifier',
                59 => 'getPersonPermissions',
                60 => 'getPersonPermits',
                61 => 'getPersonTitles',
                62 => 'getPersonUserExistsRolePermissions',
                63 => 'getPersonUserRolePermissions',
                64 => 'getPersonUsers',
                65 => 'getPersonVehicles',
                66 => 'getPersonWarthogPermits',
                67 => 'getPersons',
                68 => 'getPersonsByFarms',
                69 => 'getPersonsWithDrivers',
                70 => 'getProfessionalHunters',
                71 => 'getRequestByUuid',
                72 => 'getResponsiblePerson',
                73 => 'getStateVetsByBunrPin',
                74 => 'getTaxidermists',
                75 => 'getUserLabs',
                76 => 'getUserPersons',
                77 => 'getUserPersonsWithMembers',
                78 => 'getUserPersonsWithSpecificPermission',
                79 => 'getValidationServiceProviders',
                80 => 'getVehicles',
                81 => 'getVehiclesWherePersonDriver',
                82 => 'getVeterinarians',
                83 => 'getVeterinaryRegistrationValidators',
                84 => 'getWarthogPermitIssuerPersons',
                85 => 'isUserInPersonTeam',
                86 => 'isUserJustAMember',
                87 => 'issueWarthogPermit',
                88 => 'notifyClientOfCertificateUpload',
                89 => 'notifyStateByCertificateRequestUuid',
                90 => 'personsMovementAuthLevels',
                91 => 'postCheckPerson',
                92 => 'rejectPersonDocument',
                93 => 'removePersonDocument',
                94 => 'removeResponsiblePerson',
                95 => 'requestAccess',
                96 => 'requestBuwrCertificate',
                97 => 'saveCertificateFile',
                98 => 'savePersonFile',
                99 => 'savePersonPermissions',
                100 => 'searchCompaniesAndNaturalPersons',
                101 => 'searchPerson',
                102 => 'searchPersonsById',
                103 => 'sendInviteToPerson',
                104 => 'setDriver',
                105 => 'setResponsiblePerson',
                106 => 'showWarthogMeatApplicationFile',
                107 => 'showWarthogPermitFile',
                108 => 'signBuwrCertificateAuthorization',
                109 => 'signWarthogPermit',
                110 => 'submitPermit',
                111 => 'updatePersonAddress',
                112 => 'updatePersonIdentifier',
                113 => 'updatePersonInfo',
                114 => 'updatePersonLogo',
                115 => 'updateVehicle',
                116 => 'uploadPersonDocument',
                117 => 'verifEmail',
            ],
        ],
        'products' => [
            'class' => 'ProductsResource',
            'base' => 'products',
            'methods' => [
                0 => 'add',
                1 => 'get',
                2 => 'getAll',
                3 => 'getAllProducts',
                4 => 'getBseCertificates',
                5 => 'getIndex',
                6 => 'getPrice',
                7 => 'getProduct',
                8 => 'getProductableItems',
                9 => 'getProductableTypes',
            ],
        ],
        'public-text-entities' => [
            'class' => 'PublicTextEntitiesResource',
            'base' => 'public-text-entities',
            'methods' => [
                0 => 'getTextByEntityName',
            ],
        ],
        'qr-auth' => [
            'class' => 'QrAuthResource',
            'base' => 'qr-auth',
            'methods' => [
                0 => 'getApprove',
                1 => 'initiate',
                2 => 'status',
            ],
        ],
        'rcp' => [
            'class' => 'RcpResource',
            'base' => 'rcp',
            'methods' => [
                0 => 'confirm',
                1 => 'confirmRcp',
                2 => 'create',
                3 => 'createRcp',
                4 => 'deleteRemoveFile',
                5 => 'editRcpDriver',
                6 => 'editRcpVehiclesList',
                7 => 'generateFile',
                8 => 'generateRcpFile',
                9 => 'getAll',
                10 => 'getAllRcps',
                11 => 'getByUid',
                12 => 'getRcpByUid',
                13 => 'getShowDocument',
                14 => 'getUserRcps',
                15 => 'patchEditDriver',
                16 => 'patchEditVehiclesList',
                17 => 'patchSetSealStatus',
                18 => 'patchUpdateFile',
                19 => 'removeRcpFile',
                20 => 'saveArrival',
                21 => 'saveDeparture',
                22 => 'saveDriver',
                23 => 'saveRcpArrival',
                24 => 'saveRcpDeparture',
                25 => 'saveRcpDriver',
                26 => 'saveRcpVehicles',
                27 => 'saveVehicle',
                28 => 'searchUserRcps',
                29 => 'setSealStatus',
                30 => 'sign',
                31 => 'signRcp',
                32 => 'updateRcpFile',
                33 => 'uploadFile',
                34 => 'uploadRcpFile',
            ],
        ],
        'risks' => [
            'class' => 'RisksResource',
            'base' => 'risks',
            'methods' => [
                0 => 'assessFarms',
                1 => 'communityReports',
                2 => 'outbreaks',
            ],
        ],
        'safari-tags' => [
            'class' => 'SafariTagsResource',
            'base' => 'safari-tags',
            'methods' => [
                0 => 'addSafariTagToAnimal',
                1 => 'createSafariTag',
                2 => 'deleteDeleteSafariTag',
                3 => 'getAllSafariTags',
                4 => 'getAnimalBySafariTag',
                5 => 'getBunrSafariTags',
                6 => 'getSafariTagById',
                7 => 'getSafariTagByTag',
                8 => 'getSafariTagGroups',
                9 => 'searchSafariTagGroup',
            ],
        ],
        'scan-tags' => [
            'class' => 'ScanTagsResource',
            'base' => 'scan-tags',
            'methods' => [
                0 => 'bulkScan',
                1 => 'getAll',
                2 => 'scan',
            ],
        ],
        'scanner-devices' => [
            'class' => 'ScannerDevicesResource',
            'base' => 'scanner-devices',
            'methods' => [
                0 => 'assignVersion',
                1 => 'create',
                2 => 'destroy',
                3 => 'getIndex',
                4 => 'patchUpdate',
                5 => 'register',
                6 => 'update',
            ],
        ],
        'scanner-version' => [
            'class' => 'ScannerVersionResource',
            'base' => 'scanner-version',
            'methods' => [
                0 => 'getLastVersion',
                1 => 'getVersion',
                2 => 'saveNewVersion',
                3 => 'updateVersion',
            ],
        ],
        'send-animals' => [
            'class' => 'SendAnimalsResource',
            'base' => 'send-animals',
            'methods' => [
                0 => 'checkAnimals',
                1 => 'confirmSendAnimals',
                2 => 'createSendAnimals',
                3 => 'getAllSendAnimals',
                4 => 'getFarmMovementsReport',
                5 => 'getGenerateReport',
                6 => 'getSendAnimalsByPerson',
                7 => 'getSendAnimalsByUuid',
                8 => 'saveNewRecipient',
                9 => 'searchSendAnimals',
                10 => 'updateSendAnimals',
                11 => 'updateSendAnimalsDriver',
            ],
        ],
        'shapes-drawn' => [
            'class' => 'ShapesDrawnResource',
            'base' => 'shapes-drawn',
            'methods' => [
                0 => 'createShapesDrawn',
            ],
        ],
        'shopping-cart' => [
            'class' => 'ShoppingCartResource',
            'base' => 'shopping-cart',
            'methods' => [
                0 => 'addToCart',
                1 => 'getUserCart',
                2 => 'removeItem',
            ],
        ],
        'species' => [
            'class' => 'SpeciesResource',
            'base' => 'species',
            'methods' => [
                0 => 'assignSpeciesToZones',
                1 => 'countrySpecies',
                2 => 'countrySpeciesByIds',
                3 => 'createBreed',
                4 => 'createSpecies',
                5 => 'deleteDeleteSpecies',
                6 => 'getAllBreeds',
                7 => 'getParentSpecies',
                8 => 'getSortedSpecies',
                9 => 'getSpecies',
                10 => 'getSpeciesByFarm',
                11 => 'getSpeciesById',
                12 => 'getSpeciesMonthlyStats',
                13 => 'idsForCache',
                14 => 'patchUpdateSpecie',
                15 => 'searchBreeds',
                16 => 'searchSpecies',
            ],
        ],
        'spotter' => [
            'class' => 'SpotterResource',
            'base' => 'v1/spotter',
            'methods' => [
                0 => 'agreements',
                1 => 'agreementsCommunityGuidelines',
                2 => 'agreementsPrivacyPolicy',
                3 => 'agreementsWula',
                4 => 'authLogin',
                5 => 'authLogout',
                6 => 'authRegister',
                7 => 'cadastralDensity',
                8 => 'cadastralNearby',
                9 => 'competitions',
                10 => 'deleteSubmissionsVote',
                11 => 'getCadastralStatistics',
                12 => 'getCadastralSubmissions',
                13 => 'getCompetitions',
                14 => 'getSpecies',
                15 => 'getSubmissions',
                16 => 'getSubmissionsCounts',
                17 => 'getSubmissionsRegistrationVerifications',
                18 => 'getSubmissionsVotes',
                19 => 'getUsers',
                20 => 'getUsersAchievements',
                21 => 'leaderboards',
                22 => 'leaderboardsMyPosition',
                23 => 'me',
                24 => 'postSubmissions',
                25 => 'putMePreferences',
                26 => 'species',
                27 => 'submissions',
                28 => 'submissionsCount',
                29 => 'submissionsFlag',
                30 => 'submissionsVerifyRegistration',
                31 => 'submissionsView',
                32 => 'submissionsVote',
            ],
        ],
        'subscriptions' => [
            'class' => 'SubscriptionsResource',
            'base' => 'subscriptions',
            'methods' => [
                0 => 'createSubscription',
                1 => 'editSubscription',
                2 => 'getAllItems',
                3 => 'getAvailableSubscriptionItems',
                4 => 'getCreateSubscription',
                5 => 'getEditSubscription',
                6 => 'getItemsById',
                7 => 'getPeriods',
                8 => 'getPersonSubscriptionOrders',
                9 => 'getPersonSubscriptions',
                10 => 'getSpecificSubscriptionItems',
                11 => 'getSubscriptions',
                12 => 'getSubscriptionsForPerson',
            ],
        ],
        'telegram' => [
            'class' => 'TelegramResource',
            'base' => 'telegram',
            'methods' => [
                0 => 'getTelegramQr',
                1 => 'sendMessage',
                2 => 'webhook',
            ],
        ],
        'test-methods' => [
            'class' => 'TestMethodsResource',
            'base' => 'test-methods',
            'methods' => [
                0 => 'createTestMethod',
                1 => 'deleteTestMethod',
                2 => 'getAllTestMethod',
                3 => 'getAllTestMethods',
                4 => 'getAllTestMethodsList',
                5 => 'getCreateTestMethod',
                6 => 'getTestMethodsByTestId',
                7 => 'searchTestMethod',
                8 => 'updateTestMethod',
            ],
        ],
        'test-results' => [
            'class' => 'TestResultsResource',
            'base' => 'test-results',
            'methods' => [
                0 => 'getAllTestResultValues',
                1 => 'getSpecificTestResults',
                2 => 'storeResults',
                3 => 'storeTestResults',
            ],
        ],
        'testing-protocols' => [
            'class' => 'TestingProtocolsResource',
            'base' => 'testing-protocols',
            'methods' => [
                0 => 'createProtocol',
                1 => 'getAllProtocols',
                2 => 'getProtocolByName',
                3 => 'getProtocolBySpeciesName',
                4 => 'getProtocolTestMethods',
                5 => 'getQuarantineProtocolsByBunr',
                6 => 'getSpeciesByProtocol',
                7 => 'updateProtocol',
                8 => 'updateProtocolName',
            ],
        ],
        'tests' => [
            'class' => 'TestsResource',
            'base' => 'tests',
            'methods' => [
                0 => 'createTest',
                1 => 'deleteTest',
                2 => 'editTest',
                3 => 'getAllTest',
                4 => 'getAllTests',
                5 => 'getChildTests',
                6 => 'getCreateTest',
                7 => 'getEditTest',
                8 => 'getParentTests',
                9 => 'searchTest',
            ],
        ],
        'text-editor' => [
            'class' => 'TextEditorResource',
            'base' => 'text-editor',
            'methods' => [
                0 => 'deleteFiles',
                1 => 'editText',
                2 => 'getEntities',
                3 => 'getTextEntityFiles',
                4 => 'getTextsByEntityName',
                5 => 'save{entity}',
            ],
        ],
        'text-entities' => [
            'class' => 'TextEntitiesResource',
            'base' => 'text-entities',
            'methods' => [
                0 => 'deleteFilesFromEntity',
                1 => 'editText',
                2 => 'getTextEntities',
                3 => 'getTextEntityFiles',
                4 => 'getTextsByEntityName',
                5 => 'saveAgreement',
            ],
        ],
        'text-entity-views' => [
            'class' => 'TextEntityViewsResource',
            'base' => 'text-entity-views',
            'methods' => [
                0 => 'personAgreementView',
                1 => 'userAgreementView',
            ],
        ],
        'tp' => [
            'class' => 'TpResource',
            'base' => 'tp',
            'methods' => [
                0 => 'getV1',
            ],
        ],
        'units' => [
            'class' => 'UnitsResource',
            'base' => 'units',
            'methods' => [
                0 => 'getEuropeUnits',
                1 => 'getUsaUnits',
            ],
        ],
        'users' => [
            'class' => 'UsersResource',
            'base' => 'users',
            'methods' => [
                0 => 'agreeContract',
                1 => 'authUser',
                2 => 'ban',
                3 => 'byEmail',
                4 => 'createApiUser',
                5 => 'deleteApiUser',
                6 => 'deleteDeleteUser',
                7 => 'destroy',
                8 => 'getAllUsers',
                9 => 'getApiUser',
                10 => 'getApiUsers',
                11 => 'getAuthUserModel',
                12 => 'getIndex',
                13 => 'getMonthlyUserStats',
                14 => 'getUser',
                15 => 'getUserByEmail',
                16 => 'googleContacts',
                17 => 'linkTelegram',
                18 => 'linkWithTelegram',
                19 => 'patchBanUser',
                20 => 'patchEditUser',
                21 => 'role',
                22 => 'saveSignature',
                23 => 'search',
                24 => 'searchUser',
                25 => 'setRole',
                26 => 'signature',
                27 => 'signatureUpload',
                28 => 'statsMonthly',
                29 => 'update',
                30 => 'updateApiUser',
                31 => 'updateAvatar',
                32 => 'uploadSignatureImage',
            ],
        ],
        'vacancy-applications' => [
            'class' => 'VacancyApplicationsResource',
            'base' => 'vacancy-applications',
            'methods' => [
                0 => 'getAttachmentsDownload',
                1 => 'getIndex',
                2 => 'update',
            ],
        ],
        'vaccine-requests' => [
            'class' => 'VaccineRequestsResource',
            'base' => 'vaccine-requests',
            'methods' => [
                0 => 'animalsWithRequests',
                1 => 'attachAuthChains',
                2 => 'destroy',
                3 => 'getCheckPersonAccess',
                4 => 'getIndex',
                5 => 'getPersonRequests',
                6 => 'personsByChain',
                7 => 'putUpdate',
                8 => 'signAuthPerson',
                9 => 'signAuthorizationFile',
                10 => 'status',
                11 => 'uploadAuthorizationFile',
            ],
        ],
        'vaccine-subscriptions' => [
            'class' => 'VaccineSubscriptionsResource',
            'base' => 'vaccine-subscriptions',
            'methods' => [
                0 => 'check',
                1 => 'putSettings',
                2 => 'settings',
                3 => 'toggle',
            ],
        ],
        'vaccine-tracking' => [
            'class' => 'VaccineTrackingResource',
            'base' => 'vaccine-tracking',
            'methods' => [
                0 => 'featured',
                1 => 'getIndex',
            ],
        ],
        'vehicles' => [
            'class' => 'VehiclesResource',
            'base' => 'vehicles',
            'methods' => [
                0 => 'processBarcode',
            ],
        ],
        'verification-person' => [
            'class' => 'VerificationPersonResource',
            'base' => 'verification-person',
            'methods' => [
                0 => 'getIndex',
            ],
        ],
        'verification-user-email' => [
            'class' => 'VerificationUserEmailResource',
            'base' => 'verification-user-email',
            'methods' => [
                0 => 'getIndex',
            ],
        ],
        'warthog-meat-application' => [
            'class' => 'WarthogMeatApplicationResource',
            'base' => 'warthog-meat-application',
            'methods' => [
                0 => 'getIndex',
            ],
        ],
        'youtube-links' => [
            'class' => 'YoutubeLinksResource',
            'base' => 'youtube-links',
            'methods' => [
                0 => 'createYoutubeLink',
                1 => 'deleteDeleteLink',
                2 => 'editLink',
                3 => 'getAllYoutubeLinks',
                4 => 'searchLink',
            ],
        ],
    ];
}
